# Valid values are "daemonset" and "deployment".
# If set, agentCollector and standaloneCollector are ignored.
mode: "deployment"

config:
  exporters:
    otlp/causely:
      endpoint: mediator.causely:4317
      compression: none
      tls:
        insecure: true

  processors:
    batch:
      timeout: 1s
    k8sattributes:
      auth_type: "serviceAccount"
      passthrough: false
      extract:
        metadata:
          - k8s.pod.name
          - k8s.pod.uid
          - k8s.deployment.name
          - k8s.namespace.name
          - k8s.node.name
          - k8s.pod.start_time

  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318

  service:
    pipelines:
      traces:
        exporters:
          - otlp/causely
        processors:
          - k8sattributes
          - batch
        receivers:
          - otlp

presets:
  kubernetesAttributes:
    enabled: true

podLabels:
  sidecar.istio.io/inject: "disabled"
